{ pkgs, ... }: {
  # From sensors-detect
  boot.extraModulePackages = with pkgs.linuxPackages; [ it87 ];
  boot.kernelModules = [ "coretemp" "it87" ];

  hardware.fancontrol = {
    enable = true;
    # Generated by pwmconfig
    config = "";
  };
}

