{
  imports = [
    ./borgbackup.nix
    ./adguardhome.nix
    ./immich.nix
    ./monitoring-client.nix
    ./monitoring-server.nix
    ./paperless.nix
    ./vaultwarden.nix
    ./steam.nix
    ./obs-studio.nix
    ./nvidia.nix
    ./fonts.nix
    ./locale.nix
    ./ssh-hardening.nix
    ./system-hardening.nix
    ./default-packages.nix
    ./watchdog.nix
    ./storage-optimization.nix
    ./boot.nix
    ./coolercontrol.nix
    ./sound.nix
    ./music-player.nix
    ./jellyfin.nix
    ./jellyseer.nix
    ./navidrome.nix
    ./bazarr.nix
    ./prowlarr.nix
    ./radarr.nix
    ./sonarr.nix
    ./lidarr.nix
    ./recyclarr.nix
    ./torrent.nix
    ./usenet.nix
    ./slskd.nix
    ./reverse-proxy.nix
    ./rss.nix
    ./bluetooth.nix
  ];
}
